# Numpy practice session
## Creating an array usiny numpy

In [2]:
# 1-D array
import numpy as np
food = np.array(["samosa","pakora","raita"])
food

array(['samosa', 'pakora', 'raita'], dtype='<U6')

In [11]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

list

In [5]:
len(price)

3

In [6]:
# indexing
price[2]

5

In [7]:
price[0:] # this will give all the numbers in that list

[5, 5, 5]

In [8]:
food[1]

'pakora'

In [12]:
price.mean()

5.0

In [13]:
#zeors
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [18]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#specify
np.arange(2-20) # this is a wrong way to show the specification

array([], dtype=int32)

In [21]:
# now the correct way
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
np.arange(2,20)# even no need for space

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [24]:
# specifuc interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# specifuc interval, or we can say the table of something e.g
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [27]:
#linespace, mtlb itny numbers ayn gy jitna ham likhyn gy
np.linspace(1,100, num=10)# ab yahan total 10 number hain

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [29]:
np.linspace(1,100, num=5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [30]:
#specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [31]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Array functions

In [33]:
a=np.array([2,5,1,0,10,0.5,10.3])
a

array([ 2. ,  5. ,  1. ,  0. , 10. ,  0.5, 10.3])

In [36]:
a.sort() # tarteeb sai likh dia
a

array([ 0. ,  0.5,  1. ,  2. ,  5. , 10. , 10.3])

In [37]:
b=np.array([3, 4,10.3, 50.2,0.1])
b

array([ 3. ,  4. , 10.3, 50.2,  0.1])

In [38]:
b.sort()
b

array([ 0.1,  3. ,  4. , 10.3, 50.2])

In [41]:
c=np.concatenate((a,b))
c

array([ 0. ,  0.5,  1. ,  2. ,  5. , 10. , 10.3,  0.1,  3. ,  4. , 10.3,
       50.2])

In [42]:
c.sort()
c

array([ 0. ,  0.1,  0.5,  1. ,  2. ,  3. ,  4. ,  5. , 10. , 10.3, 10.3,
       50.2])

## 2-D arrays

In [45]:
a=np.array([[1,2,3,4,5], [5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [49]:
b=np.array([[6,7,11,12,5], [8,9,13,14,6]])
b

array([[ 6,  7, 11, 12,  5],
       [ 8,  9, 13, 14,  6]])

In [51]:
c=np.concatenate((a,b)) # to concatenate the dimention should be same
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7, 11, 12,  5],
       [ 8,  9, 13, 14,  6]])

In [52]:
c=np.concatenate((a,b), axis = 1) # to concatenate the dimention should be same
c

array([[ 1,  2,  3,  4,  5,  6,  7, 11, 12,  5],
       [ 5,  4,  3,  2,  1,  8,  9, 13, 14,  6]])

In [53]:
c=np.concatenate((a,b), axis = 0) # to concatenate the dimention should be same
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7, 11, 12,  5],
       [ 8,  9, 13, 14,  6]])

In [54]:
## 3-D
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
d.ndim

3